<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace First\tic_tac_toe_backend\Models\Shared;


/**
 * Move - A Move containing the before and after GameStates.
 * 
 * @package First\tic_tac_toe_backend\Models\Shared
 * @access public
 */
class Move
{
    /**
     * $afterState
     * 
     * @var ?array<\First\tic_tac_toe_backend\Models\Shared\MoveAfterState> $afterState
     */
	
    public ?array $afterState = null;
    
	public function __construct()
	{
		$this->afterState = null;
	}
}
