<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace First\tic_tac_toe_backend\Models\Shared;


class MoveAfterStatePossibleMovesAfterState
{
	
    public ?MoveAfterStatePossibleMovesAfterStateGrid $grid = null;
    
	
    public ?MoveAfterStatePossibleMovesAfterStateStartingMark $startingMark = null;
    
	public function __construct()
	{
		$this->grid = null;
		$this->startingMark = null;
	}
}
