<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace First\tic_tac_toe_backend\Models\Shared;


class MoveAfterState
{
	
    public ?MoveAfterStateCurrentMark $currentMark = null;
    
	
    public ?bool $gameNotStarted = null;
    
	
    public ?bool $gameOver = null;
    
	
    public ?MoveAfterStateGrid $grid = null;
    
    /**
     * $possibleMoves
     * 
     * @var ?array<\First\tic_tac_toe_backend\Models\Shared\MoveAfterStatePossibleMoves> $possibleMoves
     */
	
    public ?array $possibleMoves = null;
    
	
    public ?MoveAfterStateStartingMark $startingMark = null;
    
	
    public ?bool $tie = null;
    
	
    public ?MoveAfterStateWinner $winner = null;
    
    /**
     * $winningCells
     * 
     * @var ?array<int> $winningCells
     */
	
    public ?array $winningCells = null;
    
	public function __construct()
	{
		$this->currentMark = null;
		$this->gameNotStarted = null;
		$this->gameOver = null;
		$this->grid = null;
		$this->possibleMoves = null;
		$this->startingMark = null;
		$this->tie = null;
		$this->winner = null;
		$this->winningCells = null;
	}
}
