<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace First\tic_tac_toe_backend\Models\Shared;


class MoveParameter
{
	
    public ?int $cellIndex = null;
    
	
    public ?MoveParameterMove $move = null;
    
	public function __construct()
	{
		$this->cellIndex = null;
		$this->move = null;
	}
}
