<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace First\tic_tac_toe_backend\Models\Shared;


class MoveAfterStatePossibleMovesBeforeStateGrid
{
	
    public ?string $cells = null;
    
	public function __construct()
	{
		$this->cells = null;
	}
}
