<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace First\tic_tac_toe_backend\Models\Shared;


/**
 * Version - The package version.
 * 
 * @package First\tic_tac_toe_backend\Models\Shared
 * @access public
 */
class Version
{
	
    public ?string $version = null;
    
	public function __construct()
	{
		$this->version = null;
	}
}
